### ISSUE TITLE
Trying to make my own core

### ISSUE THREAD

**Issue by KacperSzlek** [riojking/Wheatley-Project#1]
Hey guys I'm trying to replicate your project but in the cad file i cant see a lot off mechanism's that you showcased in your videos
mainly the eyelid and the whole eye mechanisms.I love what you did could you please include these in the cad and maybe if you have any other files related to the project could you please up lode those too.

**Comment by KacperSzlek** [comment]
Never mind just saw your hackaday page

**Comment by KacperSzlek** [comment]
Right went thru the hackaday page still cant find any of those mechanisms.Can you please upload them.

**Comment by riojking** [comment]
If you're trying to make your own core, I'd recommend designing your own mechanism. That CAD isn't there because it isn't worth copying. Basically what we did was have two servos move two linkages to move the eye around, and two other servos move the eyelids. I wish I had nice CAD to share, but when I designed this, it was really unorganized, and the mechanism has a lot of slop, so replicating exactly what we did won't result in a great product. Check out these videos to see how we did it, then hopefully you can design something similar that results in a cleaner mechanism.
https://www.youtube.com/watch?v=0_HfdeOzCCg
https://www.youtube.com/watch?v=F33ShKUfKNM

**Comment by KacperSzlek** [comment]
Thanks will do, wish me god luck :).
